### ISSUE TITLE
Can we add Non-Steam games to the list?

### ISSUE THREAD

**Issue by Sebasgl23** [tuxx/steamdeckdocs#1]
For example, i have been playing Jak and Daxter : The Precursor legacy with the open goal port and i was thinking if i can add it to the games list with a tutorial of how we can install it to the Steam deck, or the page is only for Steam games?

**Comment by tuxx** [comment]
Sure, i welcome everything that has to do with steamdeck even if it is not from the official store. Maybe we can put it under the Games section for now, once we have enough content we can maybe split it up in Steam Games & Non Steam Games or something

**Comment by Sebasgl23** [comment]
I was also thinking that you could change the logo into something like this

![image](https://github.com/tuxx/steamdeckdocs/assets/33914923/b7b2b2d7-d1bb-4df6-8d2f-6d2fccb215dc)

**Comment by tuxx** [comment]
Seems like a good idea :+1:

**Comment by tuxx** [comment]
New logo is live :)

- https://github.com/tuxx/steamdeckdocs/commit/8557a4200393ce06357321edfd9bf6874ffa8fc2

**Comment by Sebasgl23** [comment]
Nice, it looks preety good

**Comment by tuxx** [comment]
![image](https://github.com/tuxx/steamdeckdocs/assets/117443/3fe412af-1f4d-4573-8d55-c9286cb12ce5)
